# Generated by Django 5.2.6 on 2026-02-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
