# Generated by Django 5.2.6 on 2025-09-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.AddField(
            model_name='profile',
            name='topimage',
            field=models.ImageField(default='images/default.jpg', upload_to='images', verbose_name='トップ画像'),
            preserve_default=False,
        ),
    ]
