# Generated by Django 5.2.6 on 2025-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_linkedin_remove_profile_twitter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='ERdiagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ER図'),
        ),
        migrations.AddField(
            model_name='profile',
            name='myapp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='フィットネスログアプリへ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='proposal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='企画書'),
        ),
        migrations.AddField(
            model_name='profile',
            name='screendiagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='画面設計図'),
        ),
        migrations.AddField(
            model_name='profile',
            name='screentransitiondiagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='画面遷移図'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(verbose_name='概要'),
        ),
    ]
