# Generated by Django 5.2.6 on 2026-04-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exerciserecord_end_time_exerciserecord_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
