# Generated by Django 5.2.6 on 2026-01-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exerciserecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciserecord',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
