# Generated by Django 5.2.6 on 2026-01-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_exerciserecord_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseschedule',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
