# Generated by Django 5.2.6 on 2026-08-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_exerciserecord_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='memo_template',
        ),
    ]
